### ISSUE TITLE
Add Periphery to official Homebrew repo

### ISSUE THREAD

**Issue by ileitch** [peripheryapp/periphery#19]
https://github.com/Homebrew/homebrew-core/pull/37504

**Comment by Dschee** [comment]
While I agree with making periphery part of Homebrew Core, I'd like to first ask if this Periphery still needs to be a `cask` instead of a plain old tool? During the time it was not open source it's clear why it needed to be a cask. But given it's open source now, I don't really understand why it still is a cask. Are there any reasons for this? @ileitch

**Comment by ileitch** [comment]
It's still convenient for some people if they prefer to install using Homebrew. I'll remove the cask once we're part of Homebrew Core.
