### ISSUE TITLE
Possible False positive with #available(iOS 14, *) 

### ISSUE THREAD

**Issue by byaruhaf** [peripheryapp/periphery#240]
Here is the code below:

```swift
var listView: some View {
    List {
      if #available(iOS 14, *) {
        makeSectionList {
          listContentView
        }
      } else {
        makeList {
          listContentView
        }
      }
    }
      .if(!allowDelete) {
        $0.gesture(
          DragGesture().onChanged { _ in
            UIApplication.dismissKeyboard()
          }
        )
      }
      .accessibility(identifier: "contentListView")
  }

  func makeList<Content: View>(
    @ViewBuilder content: () -> Content
  ) -> some View {
    Section(header: header, content: content)
      .listRowInsets(EdgeInsets())
  }

```

Periphery reported 

`ContentListView.swift:176:8: warning: Function 'makeList(content:)' is unused
`

yet `makeList(content:)` is used in the ios13.

**Comment by ileitch** [comment]
`#available` is a compile-time condition, and it's dependent on your deployment target which branch is compiled. Unfortunately Periphery has no data for the branch that isn't compiled, simply because the compiler doesn't provide it. You can workaround this by adding a `// periphery:ignore` comment above `makeList(content:)`.
