### ISSUE TITLE
Support for filtering the report based on provided declarations

### ISSUE THREAD

**Issue by crtgregoric** [peripheryapp/periphery#259]
It would be great to have the ability to provide an input parameter that specifies which declarations should be included in the report. The parameter would be optional and default to the current implementation if not present. When present the report would include only the provided declarations.

Proposed input parameter:
`--reported-declarations <comma separated declarations>`

Reasoning:
Using Periphery for the first time on a large project that has been around for a while can be a bit overwhelming. It would be easier to filter the output to show only certain declarations. This way the cleanup could be a bit more organized and easier to perform in smaller steps.

**Comment by ileitch** [comment]
Thank you for the suggestion, though I don't believe this is practical enough to be implemented in Periphery. The issue is that for a declaration to be uniquely identified, we also need it's source location. Specifying one or more unique declarations like this via a parameter would be quite cumbersome.

I think a better approach is to just copy the full results into a text editor and then filter out the results you need. A text editor gives you much more control over filtering, and doesn't require you to re-run Periphery.
