### ISSUE TITLE
Is there a way to analyze development pods?

### ISSUE THREAD

**Issue by Alarson93** [peripheryapp/periphery#297]
_For clarity - I'm going to say "development pods" when talking about my local pod features and "external pods" when talking about pods pulled from the public Cocoapods trunk._

The project I'm working on has a highly modular architecture. Each feature is a development pod stored in my project's repo. This means that while the source code for the development pod lives in my repo, it is accessed as if it were a third-party library.

I would like to be able to use this tool to find unused code in these development pods, but NOT external pods. Unfortunately I can't quite figure it out.

I scan my primary target (which imports all pods), but the development pod code is not analyzed. I've tried enabling the schemes for these development pods and manually specifying them as targets/schemes through the YAML file, but that leads to some strange behavior where `swift-frontend` process fills up my CPU resources indefinitely.

I'm wondering if you know how to accomplish this or, if the feature is not currently supported, could it be added in the future?

I'm pretty sure this can be accomplished as SwiftLint is able to properly lint my main project code, my development pods, but  ignore external pods. So, if the feature does not yet exist and this is something you would consider adding, I would recommend looking into how SwiftLint accomplishes it's linting.

In the meantime - I'll continue experimenting! If I find a solution, I'll post it here.

Thank you!

**Comment by ileitch** [comment]
This should be possible, it sounds like the real issue is with `swift-frontend` getting stuck. With your development pods also passed to `--targets`, you can perform a scan along with the `--verbose` to see the underlying `xcodebuild` command that is being performed. You can copy and run this command in another shell and attempt to diagnose why it may be getting stuck.

> I'm pretty sure this can be accomplished as SwiftLint is able to properly lint my main project code, my development pods, but ignore external pods. So, if the feature does not yet exist and this is something you would consider adding, I would recommend looking into how SwiftLint accomplishes it's linting.

SwiftLint is not really comparable in this regard. Periphery needs to analyze your targets and project as a whole in order to build a graph of relationships between declarations. This is a far more complex task than simply analyzing each source file individually, which is what SwiftLint does.

**Comment by Alarson93** [comment]
Your comment about passing the pods via targets was helpful. I was passing my development pods into schemes instead of targets. Swapping those around seems to have resolved the issue.

For future reference, here is an example:

Let's say I have a pod called `Potato`. It exists in an app called `MyApp`. I see these schemes in Xcode's "Manage Schemes" window:
* MyApp
* Potato
* Potato-Potato
* Potato-Unit-Tests

Your YML file (or command flags) should contain the following:
```schemes:
- MyApp
targets:
- MyApp
- Potato```

It now looks like everything is working! It even seems to do a good job at identifying if `Potato` code is being used in `MyApp`.

Thank you very much!
