### ISSUE TITLE
Unable to run with error "Reason: image not found"

### ISSUE THREAD

**Issue by shtnkgm** [peripheryapp/periphery#399]
When I run `mint run periphery` command in my environment, I get the following error message and cannot run periphery.
Is there any solution to this problem?

```bash
% mint run periphery                   
dyld: Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib
  Referenced from: /usr/local/lib/mint/packages/github.com_peripheryapp_periphery/build/2.8.1/periphery
  Reason: image not found
zsh: abort      mint run periphery
```

**Environment**

 - periphery: 2.8.1
 - macOS: Big Sur 11.4
 - Xcode: 12.5
 - Swift: Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
 - mint: 0.16.0

**Relevant Issues**

 - https://github.com/uber/mockolo/issues/108
 - https://github.com/uber/needle/issues/366
 - https://github.com/peripheryapp/periphery/issues/81

**Comment by ileitch** [comment]
It appears that Periphery is not longer compatible with Mint, because Mint does not bundle `lib_InternalSwiftSyntaxParser.dylib` into the installation directory. Here's a similar issue: https://github.com/yonaskolb/Mint/issues/211. It also looks like Mint development has stalled, it's almost 1 year since the last release.

I'm sorry but I think the only option here is to use SPM directly, or use the prebuilt binary releases.

**Comment by mthole** [comment]
@ileitch FWIW, it seems like `mint` is working nicely with `periphery` again. Without having seen the deprecation of mint, I used it today to install a specific SHA of periphery for testing the SPM local packages branch. The mint install worked fine.
