### ISSUE TITLE
False positive with initializer requirements in protocols

### ISSUE THREAD

**Issue by sdc-78** [peripheryapp/periphery#413]
Hello,

With the following code:
```swift
protocol Something {

    var key: String { get }

    init(with key: String) // <== warning here
}

extension Something {

    func run() {
        print(key)
    }
}

final class Foo: Something {

    let key: String

    init(with key: String) {
        self.key = key
    }
}

Foo(with: "the-key").run()
```

Periphery 2.8.1 reports a warning:
```
warning: Initializer 'init(with:)' is unused
```

**Comment by ileitch** [comment]
This warning is actually correct. The initializer is unused in the protocol because when you call `Foo(with:)` you're calling the initializer directly on `Foo`. The protocol requirement is irrelevant, you can comment out `init(with key: String)` in the protocol and the code will still compile.

A situation where `init(with key: String)` _would_ be used is when the protocol is used to specialize a generic function that initializes a given type, e.g:

```swift
func make<T: Something>(_ type: T.Type) -> T {
    return type.init(with: "key")
}
```

**Comment by sdc-78** [comment]
Indeed, you are right. Sorry for this false false-positive!
