### ISSUE TITLE
SwiftUI previews back to being un-retained in Swift 5.7?

### ISSUE THREAD

**Issue by ts0l** [peripheryapp/periphery#503]
just tried out the Xcode 14 beta with Periphery, and with the Swift 5.7 toolchain, I was getting warnings that SwiftUI PreviewProvider-conforming structs were unused. AFAIK this was resolved in 2.0.0, and I was on 2.9.0. wondering if it's worth investigation! cheers :)

**Comment by ileitch** [comment]
Hmm, none of the tests for previews are failing with Xcode 14. Could you please provide a demo project with the issue?

**Comment by ileitch** [comment]
Closing due to no response. I'll happily investigate further if you can provide a demo project.

**Comment by advantis** [comment]
In our case the reason was obvious and 100% reproducible. If we model our `PreviewProvider`s as enums - they don't get retained by Periphery:
```swift
enum SomeView_Previews: PreviewProvider {
    static var previews: some View {
        // …
    }
}
```

Even the title of the [original PR](https://github.com/peripheryapp/periphery/pull/134) reads as:
> Retain **class/structs** that conform to SwiftUI's PreviewProvider

And it's indeed only concerned about [those types](https://github.com/peripheryapp/periphery/pull/134/files#diff-2b5170f6ca3245e1f8c8d720af89c5f837ee199c476ce3245b877699e4717f28R22) of declarations.

If we change the declaration above from `enum` to `struct` - the warnings go away. The Periphery version we use is 2.11.0. I can also provide a sample project if needed.

**Comment by ileitch** [comment]
Thanks @advantis, I've pushed a fix for this and it'll be included in the next release.

**Comment by advantis** [comment]
Thank you @ileitch for such a great software that really has no analogues!
