### ISSUE TITLE
error: (ParserError) The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax

### ISSUE THREAD

**Issue by leogdion** [peripheryapp/periphery#510]
Included SPM and received the following error:
> error: (ParserError) The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax

**Comment by niehusstaab** [comment]
To add my 2 cents, I get this error when running `periphery scan` on my iOS app. 
I do have multiple versions of Xcode installed (not sure if that would mess with it in any way), under build_arguments in my .periphery.yml file, I'm specifying `-sdk iphonesimulator` and I'm limiting architectures that get built with `-arch x86_64` (due to some binary dependencies I'm using not having compiled the arm64 arch for simulators). It manages to build all my specified schemes/targets successfully, but as soon as it gets to indexing it crashes. (even running periphery scan with the --verbose flag didnt get me any more information about the crash or failing command)
```
* Indexing...
Error: The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax
```

**Comment by ileitch** [comment]
Please try again using v2.10.0 and report back if the problem persists, thanks!
