### ISSUE TITLE
“periphery” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by ZevEisenberg** [peripheryapp/periphery#57]
after installing from HomeBrew on Catalina 10.15.1, I get this error when I try to run periphery:

![image](https://user-images.githubusercontent.com/464574/68411191-00c6cd80-0158-11ea-97fa-776f510daa7f.png)

Guessing it’s something to do with code signing?

**Comment by ileitch** [comment]
You need to allow in Security & Privacy on the General tab. Note that Periphery doesn't currently work with Xcode 11, though if you're feeling adventurous there's an Xcode 11 branch: https://github.com/peripheryapp/periphery/tree/xcode11

**Comment by ZevEisenberg** [comment]
Is there any way to avoid having to approve it? Can you sign it with Developer ID or build it on the user’s machine or something to that effect? The current behavior is pretty user-hostile and hard to figure out how to proceed. (I ended up doing `xattr -d com.apple.quarantine /usr/local/bin/periphery` because I’m old-school like that 😁.)

**Comment by ileitch** [comment]
Oh absolutely there's room for improvement here, I've just had very little time to devote to Periphery recently.

**Comment by ermik** [comment]
A more GUI approach is to find the executable:
```sh
which periphery
```
open that directory and Ctrl-Click (or right click) the executable and select `Open`. This will show you a warning prompt with an `Open` option which would whitelist it for future execution.

Since it may be symlinked (e.g. if installed via Homebrew) one quick way to open the finder into that directory is to run:
```sh
open $(dirname $(realpath $(which periphery)))
```

**Comment by saltyskip** [comment]
Give access to terminal to access unverified apps
![image](https://user-images.githubusercontent.com/14796429/72408645-c5bfc680-37a6-11ea-8325-b56147796df8.png)

**Comment by whiskey** [comment]
> Give access to terminal to access unverified apps

Terrible idea because it allows access for ALL unsigned apps which is not what I want. I'd prefer [Zev's](https://github.com/peripheryapp/periphery/issues/57#issuecomment-551207796) way by using  `xattr -d com.apple.quarantine /usr/local/bin/periphery` on that particular binary.

Maybe I'm getting old too… 🤔😃

**Comment by ileitch** [comment]
Please see here for the status of Periphery: https://github.com/peripheryapp/periphery/issues/66
